<a href="https://colab.research.google.com/github/GopikaDA/python-DA_coding_challenges/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  NumPy Arrays & Operations

## Array Creation

In [ ]:
import numpy as np

one_d_array = np.array([1,2,3,4,5,6,7])
one_d_array

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
print(one_d_array)

[1 2 3 4 5 6 7]


In [ ]:
oned_array=np.arange(3,16,3)
oned_array

array([ 3,  6,  9, 12, 15])