In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)            # [1 2 3 4]


In [ ]:
b = np.arange(1, 10, 2)
print(b)            # [1 3 5 7 9]


In [ ]:
c = np.linspace(0, 1, 5)
print(c)            # [0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)   # 2  → 2D array
print(arr.shape)  # (2, 3) → 2 rows, 3 columns
print(arr.size)   # 6 → total elements
print(arr.dtype)  # int64 → data type


In [ ]:
print(np.zeros((2,3)))   # 2x3 array filled with 0
print(np.ones((2,3)))    # 2x3 array filled with 1
print(np.full((2,3), 7)) # 2x3 array filled with 7


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])     # 20 → single element
print(arr[1:4])   # [20 30 40] → slice
print(arr[-1])    # 50 → last element


In [ ]:
arr = np.array( [ [ [1,2,3] , [4,5,6] ] , [ [7,8,9] , [10,11,12] ] ] )


In [ ]:
arr = np.array([1, 2, 3])
print(arr + 5)    # [6 7 8]
print(arr * 2)    # [2 4 6]
print(arr ** 2)   # [1 4 9]
print(arr % 2)    # [1 0 1]

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())   # 15
print(arr.mean())  # 3.0
print(arr.max())   # 5
print(arr.min())   # 1
print(arr.std())   # 1.414


In [ ]:
print(np.random.rand(3))      # [0.43 0.87 0.12] → random floats between 0 and 1
print(np.random.randint(1, 10, 5)) # [3 7 1 9 4] → 5 random integers from 1 to 9


In [ ]:
arr = np.arange(1, 7)
print(arr.reshape(2, 3))
# [[1 2 3]
#  [4 5 6]]

print(arr.flatten())  # [1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
# [[1 2 3]
#  [4 5 6]]

print(np.hstack((a, b)))
# [1 2 3 4 5 6]


In [ ]:
arr = np.arange(1, 7)
print(np.split(arr, 3))
# [array([1, 2]), array([3, 4]), array([5, 6])]

print(np.array_split(arr, 4))
# can split unevenly


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a, b)))
# [1 2 3 4 5 6]


In [ ]:
arr = np.array([10, 20, 30, 40])

print(np.where(arr > 20, "High", "Low"))
# ['Low' 'Low' 'High' 'High']

print(np.clip(arr, 15, 35))
# [15 20 30 35]


In [ ]:
arr = np.array([0, 1, 2, 0])
print(np.any(arr))   # True → at least one non-zero
print(np.all(arr))   # False → not all are non-zero

In [ ]:
arr = np.array([3, 1, 2, 1, 3])
print(np.sort(arr))      # [1 1 2 3 3]
print(np.unique(arr))    # [1 2 3]


In [ ]:
arr = np.array([1, 4, 9])
print(np.abs([-1, -2, 3]))   # [1 2 3]
print(np.sqrt(arr))          # [1. 2. 3.]
print(np.log(arr))           # [0.   1.386 2.197]

In [ ]:
import numpy as np

arr = np.arange(6)      # [0 1 2 3 4 5]
reshaped = arr.reshape(2, 3)
print(reshaped)


In [ ]:
arr = np.arange(12)     # [0 1 2 ... 11]
reshaped = arr.reshape(3, 4)
print(reshaped)


In [ ]:
arr = np.arange(8)
reshaped = arr.reshape(2, 2, 2)
print(reshaped)


In [ ]:
arr = np.arange(12)
reshaped = arr.reshape(3, 2, 2)
print(reshaped)


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(-1))


In [ ]:
arr = np.array([[10,20],[30,40],[50,60]])
print(arr.reshape(6))


In [ ]:
arr = np.arange(12)
print(arr.reshape(4,3))
print(arr.reshape(2,2,3))

In [ ]:
arr = np.arange(12).reshape(3,2,2)
print(arr.reshape(12))


In [ ]:
arr = np.arange(12).reshape(2,2,3)
print(arr.reshape(4,3))


In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr.ravel())


In [ ]:
arr = np.array([[5,6],[7,8]])
print(arr.flatten())


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)
